---
- name: Install Galera PKGS
  dnf:
   name:
    - galera
    - rsync
   state: latest

- name: Allow Galera Ports
  firewalld: 
   port: "{{ item }}"
   zone: public
   state: enabled
   permanent: true
  loop:
   - 4567/tcp
   - 4567/udp
   - 4444/tcp
   - 4568/tcp

  notify:
   - firewalld_reload
- meta: flush_handlers   
       
- name: Push Galera Config File
  template: src=galera.cnf.j2 dest=/etc/my.cnf.d/galera.cnf

- name: Start Galera Cluster
  command: galera_new_cluster
  when: ansible_host == "192.168.122.31"

- name: Start MariaDB on DB2 Server
  systemd: name=mariadb state=started  
  when: ansible_host == "192.168.122.32"

    
