---
- name: Create employee DB
  mysql_db:
    name: employee_db
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock   #for maria10.4

- name: Send DB SQL file
  copy: src=employee_db.sql dest=/root
    
- name: Restore DB
  #shell: mysql -uroot employee_db < /root/employee_db.sql 
  mysql_db:
    name: employee_db
    state: import
    target: /root/employee_db.sql
    login_unix_socket: /var/lib/mysql/mysql.sock   #for maria10.4
- name: Create appuser for DB
  mysql_user:
    name: appuser
    password: appuser
    priv: 'employee_db.*:ALL'
    host: '%'
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock   #for maria10.4
  no_log: True     #Prevent ansible from logging password
